### ISSUE TITLE
Types are broken

### ISSUE THREAD

**Issue by hopkins385** [supabase-community/seed#197]
# Bug report

## Describe the bug
Types are "gone".
Return type of createSeedClient is "never".
type SeedClient is no longer exported.

```js
// dist > assets > index.d.ts
declare const createSeedClient: () => never;
export { createSeedClient };
```

```js
import type { SeedClient } from '@snaplet/seed';
// Error: Module '"@snaplet/seed"' has no exported member 'SeedClient'.ts
```

```js
  const seed = await createSeedClient();
// Error: 'await' has no effect on the type of this expression

  await seed.$resetDatabase();
// Error: Property '$resetDatabase' does not exist on type 'never'
```

## Version:
"@snaplet/seed": "^0.98.0",

**Comment by hopkins385** [comment]
mhh.. types are back now .. lul? .. might be something on my side

**Comment by Fadi729** [comment]
I'm facing the same issue. How did you fix it? I'm using version `0.98.0` as well.

**Comment by hopkins385** [comment]
I honestly don't exactly know. I'm on vscode insiders and maybe I just updated to the newest release? Or just did a vscode restart? Or updated my vscode plugins? idk. Maybe also a `npm ci` (clean install) helped, after installing other packages.

**Comment by farmisen** [comment]
@Fadi729  running:
```shell
pnpm dlx @snaplet/seed generate # (npx @snaplet/seed sync from npm)
```
fixed it for me.

**Comment by Fadi729** [comment]
@farmisen Thanks it's working now. However my CI pipeline is still failing for the same reason. Would it make sense to run this command in my CI pipeline ?

**Comment by lightstrike** [comment]
Thanks @farmisen, that worked for me too. 

@hopkins385 It is strange that types don't work out of the box after installation, worth reopening this issue IMHO.
